# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Verdaccio
version: "1.2.2"
slug: verdaccio
description: Verdaccio add-on
url: "https://github.com/giomengu/verdaccio-ha/tree/main/verdaccio"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ingress: true,
ingress_port: 4873,
boot: auto
startup: services
panel_icon: "verdaccio-tiny-uk-no-bg.svg",
ports:
  4873/tcp: 4873
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
